//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "BlazeServiceSoap", Namespace = "http://tempuri.org/")]
public partial class BlazeService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback BlazeInvokeOperationCompleted;

    /// <remarks/>
    public BlazeService()
    {
        this.Url = "http://172.29.30.15/MSSQLUAT005/NI_WS_Blaze_STRING/BlazeService.asmx";
    }

    /// <remarks/>
    public event BlazeInvokeCompletedEventHandler BlazeInvokeCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BlazeInvoke", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string BlazeInvoke(string arg0)
    {
        object[] results = this.Invoke("BlazeInvoke", new object[] {
                    arg0});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginBlazeInvoke(string arg0, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("BlazeInvoke", new object[] {
                    arg0}, callback, asyncState);
    }

    /// <remarks/>
    public string EndBlazeInvoke(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void BlazeInvokeAsync(string arg0)
    {
        this.BlazeInvokeAsync(arg0, null);
    }

    /// <remarks/>
    public void BlazeInvokeAsync(string arg0, object userState)
    {
        if ((this.BlazeInvokeOperationCompleted == null))
        {
            this.BlazeInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBlazeInvokeOperationCompleted);
        }
        this.InvokeAsync("BlazeInvoke", new object[] {
                    arg0}, this.BlazeInvokeOperationCompleted, userState);
    }

    private void OnBlazeInvokeOperationCompleted(object arg)
    {
        if ((this.BlazeInvokeCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.BlazeInvokeCompleted(this, new BlazeInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void BlazeInvokeCompletedEventHandler(object sender, BlazeInvokeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BlazeInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal BlazeInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
