//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EquifaxCr_WebServices_Reportes INFORM - ENRICH - EMPOWERSoap", Namespace="https://webservices.equifax.cr")]
public partial class EquifaxCr_WebServices_ReportesINFORMENRICHEMPOWER : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback estudio_personas_fisicasOperationCompleted;
    
    private System.Threading.SendOrPostCallback obtener_datos_vehiculoOperationCompleted;
    
    private System.Threading.SendOrPostCallback categorias_informacionOperationCompleted;
    
    private System.Threading.SendOrPostCallback estudio_personas_juridicasOperationCompleted;
    
    private System.Threading.SendOrPostCallback categorias_informacion_juridicasOperationCompleted;
    
    private System.Threading.SendOrPostCallback EFX_Validar_UsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback Extranjeros_por_IdentificacionOperationCompleted;
    
    private System.Threading.SendOrPostCallback Obtener_UsuarioWSOperationCompleted;
    
    private System.Threading.SendOrPostCallback Enviar_CorreoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Listas_InternacionalesOperationCompleted;
    
    private System.Threading.SendOrPostCallback Estudio_360_FisicoOperationCompleted;
    
    /// <remarks/>
    public EquifaxCr_WebServices_ReportesINFORMENRICHEMPOWER() {
        this.Url = "https://webservices.equifax.cr/webservices/efx_consultas.asmx";
    }
    
    /// <remarks/>
    public event estudio_personas_fisicasCompletedEventHandler estudio_personas_fisicasCompleted;
    
    /// <remarks/>
    public event obtener_datos_vehiculoCompletedEventHandler obtener_datos_vehiculoCompleted;
    
    /// <remarks/>
    public event categorias_informacionCompletedEventHandler categorias_informacionCompleted;
    
    /// <remarks/>
    public event estudio_personas_juridicasCompletedEventHandler estudio_personas_juridicasCompleted;
    
    /// <remarks/>
    public event categorias_informacion_juridicasCompletedEventHandler categorias_informacion_juridicasCompleted;
    
    /// <remarks/>
    public event EFX_Validar_UsuarioCompletedEventHandler EFX_Validar_UsuarioCompleted;
    
    /// <remarks/>
    public event Extranjeros_por_IdentificacionCompletedEventHandler Extranjeros_por_IdentificacionCompleted;
    
    /// <remarks/>
    public event Obtener_UsuarioWSCompletedEventHandler Obtener_UsuarioWSCompleted;
    
    /// <remarks/>
    public event Enviar_CorreoCompletedEventHandler Enviar_CorreoCompleted;
    
    /// <remarks/>
    public event Listas_InternacionalesCompletedEventHandler Listas_InternacionalesCompleted;
    
    /// <remarks/>
    public event Estudio_360_FisicoCompletedEventHandler Estudio_360_FisicoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/estudio_personas_fisicas", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string estudio_personas_fisicas(string referencia, string cedula, string usuario, string clave, string usuario_datum) {
        object[] results = this.Invoke("estudio_personas_fisicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginestudio_personas_fisicas(string referencia, string cedula, string usuario, string clave, string usuario_datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("estudio_personas_fisicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endestudio_personas_fisicas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void estudio_personas_fisicasAsync(string referencia, string cedula, string usuario, string clave, string usuario_datum) {
        this.estudio_personas_fisicasAsync(referencia, cedula, usuario, clave, usuario_datum, null);
    }
    
    /// <remarks/>
    public void estudio_personas_fisicasAsync(string referencia, string cedula, string usuario, string clave, string usuario_datum, object userState) {
        if ((this.estudio_personas_fisicasOperationCompleted == null)) {
            this.estudio_personas_fisicasOperationCompleted = new System.Threading.SendOrPostCallback(this.Onestudio_personas_fisicasOperationCompleted);
        }
        this.InvokeAsync("estudio_personas_fisicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum}, this.estudio_personas_fisicasOperationCompleted, userState);
    }
    
    private void Onestudio_personas_fisicasOperationCompleted(object arg) {
        if ((this.estudio_personas_fisicasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.estudio_personas_fisicasCompleted(this, new estudio_personas_fisicasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/obtener_datos_vehiculo", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string obtener_datos_vehiculo(string placa, string usuario, string clave, string usuario_datum) {
        object[] results = this.Invoke("obtener_datos_vehiculo", new object[] {
                    placa,
                    usuario,
                    clave,
                    usuario_datum});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginobtener_datos_vehiculo(string placa, string usuario, string clave, string usuario_datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("obtener_datos_vehiculo", new object[] {
                    placa,
                    usuario,
                    clave,
                    usuario_datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endobtener_datos_vehiculo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void obtener_datos_vehiculoAsync(string placa, string usuario, string clave, string usuario_datum) {
        this.obtener_datos_vehiculoAsync(placa, usuario, clave, usuario_datum, null);
    }
    
    /// <remarks/>
    public void obtener_datos_vehiculoAsync(string placa, string usuario, string clave, string usuario_datum, object userState) {
        if ((this.obtener_datos_vehiculoOperationCompleted == null)) {
            this.obtener_datos_vehiculoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onobtener_datos_vehiculoOperationCompleted);
        }
        this.InvokeAsync("obtener_datos_vehiculo", new object[] {
                    placa,
                    usuario,
                    clave,
                    usuario_datum}, this.obtener_datos_vehiculoOperationCompleted, userState);
    }
    
    private void Onobtener_datos_vehiculoOperationCompleted(object arg) {
        if ((this.obtener_datos_vehiculoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.obtener_datos_vehiculoCompleted(this, new obtener_datos_vehiculoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/categorias_informacion", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string categorias_informacion(string cedula, string usuario, string clave, string categoria) {
        object[] results = this.Invoke("categorias_informacion", new object[] {
                    cedula,
                    usuario,
                    clave,
                    categoria});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begincategorias_informacion(string cedula, string usuario, string clave, string categoria, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("categorias_informacion", new object[] {
                    cedula,
                    usuario,
                    clave,
                    categoria}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endcategorias_informacion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void categorias_informacionAsync(string cedula, string usuario, string clave, string categoria) {
        this.categorias_informacionAsync(cedula, usuario, clave, categoria, null);
    }
    
    /// <remarks/>
    public void categorias_informacionAsync(string cedula, string usuario, string clave, string categoria, object userState) {
        if ((this.categorias_informacionOperationCompleted == null)) {
            this.categorias_informacionOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncategorias_informacionOperationCompleted);
        }
        this.InvokeAsync("categorias_informacion", new object[] {
                    cedula,
                    usuario,
                    clave,
                    categoria}, this.categorias_informacionOperationCompleted, userState);
    }
    
    private void Oncategorias_informacionOperationCompleted(object arg) {
        if ((this.categorias_informacionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.categorias_informacionCompleted(this, new categorias_informacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/estudio_personas_juridicas", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string estudio_personas_juridicas(string referencia, string cedula, string usuario, string clave, string usuario_datum) {
        object[] results = this.Invoke("estudio_personas_juridicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginestudio_personas_juridicas(string referencia, string cedula, string usuario, string clave, string usuario_datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("estudio_personas_juridicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endestudio_personas_juridicas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void estudio_personas_juridicasAsync(string referencia, string cedula, string usuario, string clave, string usuario_datum) {
        this.estudio_personas_juridicasAsync(referencia, cedula, usuario, clave, usuario_datum, null);
    }
    
    /// <remarks/>
    public void estudio_personas_juridicasAsync(string referencia, string cedula, string usuario, string clave, string usuario_datum, object userState) {
        if ((this.estudio_personas_juridicasOperationCompleted == null)) {
            this.estudio_personas_juridicasOperationCompleted = new System.Threading.SendOrPostCallback(this.Onestudio_personas_juridicasOperationCompleted);
        }
        this.InvokeAsync("estudio_personas_juridicas", new object[] {
                    referencia,
                    cedula,
                    usuario,
                    clave,
                    usuario_datum}, this.estudio_personas_juridicasOperationCompleted, userState);
    }
    
    private void Onestudio_personas_juridicasOperationCompleted(object arg) {
        if ((this.estudio_personas_juridicasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.estudio_personas_juridicasCompleted(this, new estudio_personas_juridicasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/categorias_informacion_juridicas", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string categorias_informacion_juridicas(string cedula_juridica, string usuario, string clave, string categoria) {
        object[] results = this.Invoke("categorias_informacion_juridicas", new object[] {
                    cedula_juridica,
                    usuario,
                    clave,
                    categoria});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begincategorias_informacion_juridicas(string cedula_juridica, string usuario, string clave, string categoria, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("categorias_informacion_juridicas", new object[] {
                    cedula_juridica,
                    usuario,
                    clave,
                    categoria}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endcategorias_informacion_juridicas(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void categorias_informacion_juridicasAsync(string cedula_juridica, string usuario, string clave, string categoria) {
        this.categorias_informacion_juridicasAsync(cedula_juridica, usuario, clave, categoria, null);
    }
    
    /// <remarks/>
    public void categorias_informacion_juridicasAsync(string cedula_juridica, string usuario, string clave, string categoria, object userState) {
        if ((this.categorias_informacion_juridicasOperationCompleted == null)) {
            this.categorias_informacion_juridicasOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncategorias_informacion_juridicasOperationCompleted);
        }
        this.InvokeAsync("categorias_informacion_juridicas", new object[] {
                    cedula_juridica,
                    usuario,
                    clave,
                    categoria}, this.categorias_informacion_juridicasOperationCompleted, userState);
    }
    
    private void Oncategorias_informacion_juridicasOperationCompleted(object arg) {
        if ((this.categorias_informacion_juridicasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.categorias_informacion_juridicasCompleted(this, new categorias_informacion_juridicasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/EFX_Validar_Usuario", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string EFX_Validar_Usuario(string usuario, string clave, int programa, int plataforma) {
        object[] results = this.Invoke("EFX_Validar_Usuario", new object[] {
                    usuario,
                    clave,
                    programa,
                    plataforma});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEFX_Validar_Usuario(string usuario, string clave, int programa, int plataforma, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EFX_Validar_Usuario", new object[] {
                    usuario,
                    clave,
                    programa,
                    plataforma}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndEFX_Validar_Usuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void EFX_Validar_UsuarioAsync(string usuario, string clave, int programa, int plataforma) {
        this.EFX_Validar_UsuarioAsync(usuario, clave, programa, plataforma, null);
    }
    
    /// <remarks/>
    public void EFX_Validar_UsuarioAsync(string usuario, string clave, int programa, int plataforma, object userState) {
        if ((this.EFX_Validar_UsuarioOperationCompleted == null)) {
            this.EFX_Validar_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEFX_Validar_UsuarioOperationCompleted);
        }
        this.InvokeAsync("EFX_Validar_Usuario", new object[] {
                    usuario,
                    clave,
                    programa,
                    plataforma}, this.EFX_Validar_UsuarioOperationCompleted, userState);
    }
    
    private void OnEFX_Validar_UsuarioOperationCompleted(object arg) {
        if ((this.EFX_Validar_UsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EFX_Validar_UsuarioCompleted(this, new EFX_Validar_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/Extranjeros_por_Identificacion", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode Extranjeros_por_Identificacion(string referencia, string id, string usuario, string clave, string usuario_datum) {
        object[] results = this.Invoke("Extranjeros_por_Identificacion", new object[] {
                    referencia,
                    id,
                    usuario,
                    clave,
                    usuario_datum});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExtranjeros_por_Identificacion(string referencia, string id, string usuario, string clave, string usuario_datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Extranjeros_por_Identificacion", new object[] {
                    referencia,
                    id,
                    usuario,
                    clave,
                    usuario_datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndExtranjeros_por_Identificacion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void Extranjeros_por_IdentificacionAsync(string referencia, string id, string usuario, string clave, string usuario_datum) {
        this.Extranjeros_por_IdentificacionAsync(referencia, id, usuario, clave, usuario_datum, null);
    }
    
    /// <remarks/>
    public void Extranjeros_por_IdentificacionAsync(string referencia, string id, string usuario, string clave, string usuario_datum, object userState) {
        if ((this.Extranjeros_por_IdentificacionOperationCompleted == null)) {
            this.Extranjeros_por_IdentificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtranjeros_por_IdentificacionOperationCompleted);
        }
        this.InvokeAsync("Extranjeros_por_Identificacion", new object[] {
                    referencia,
                    id,
                    usuario,
                    clave,
                    usuario_datum}, this.Extranjeros_por_IdentificacionOperationCompleted, userState);
    }
    
    private void OnExtranjeros_por_IdentificacionOperationCompleted(object arg) {
        if ((this.Extranjeros_por_IdentificacionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Extranjeros_por_IdentificacionCompleted(this, new Extranjeros_por_IdentificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/Obtener_UsuarioWS", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode Obtener_UsuarioWS(string Usuario, string Clave, int Programa) {
        object[] results = this.Invoke("Obtener_UsuarioWS", new object[] {
                    Usuario,
                    Clave,
                    Programa});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtener_UsuarioWS(string Usuario, string Clave, int Programa, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Obtener_UsuarioWS", new object[] {
                    Usuario,
                    Clave,
                    Programa}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndObtener_UsuarioWS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void Obtener_UsuarioWSAsync(string Usuario, string Clave, int Programa) {
        this.Obtener_UsuarioWSAsync(Usuario, Clave, Programa, null);
    }
    
    /// <remarks/>
    public void Obtener_UsuarioWSAsync(string Usuario, string Clave, int Programa, object userState) {
        if ((this.Obtener_UsuarioWSOperationCompleted == null)) {
            this.Obtener_UsuarioWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtener_UsuarioWSOperationCompleted);
        }
        this.InvokeAsync("Obtener_UsuarioWS", new object[] {
                    Usuario,
                    Clave,
                    Programa}, this.Obtener_UsuarioWSOperationCompleted, userState);
    }
    
    private void OnObtener_UsuarioWSOperationCompleted(object arg) {
        if ((this.Obtener_UsuarioWSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Obtener_UsuarioWSCompleted(this, new Obtener_UsuarioWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/Enviar_Correo", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode Enviar_Correo(string Usuario, string Clave, string Correo_Remitente, string Correos_Destinatarios, string Asunto, string Cuerpo_Correo) {
        object[] results = this.Invoke("Enviar_Correo", new object[] {
                    Usuario,
                    Clave,
                    Correo_Remitente,
                    Correos_Destinatarios,
                    Asunto,
                    Cuerpo_Correo});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnviar_Correo(string Usuario, string Clave, string Correo_Remitente, string Correos_Destinatarios, string Asunto, string Cuerpo_Correo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Enviar_Correo", new object[] {
                    Usuario,
                    Clave,
                    Correo_Remitente,
                    Correos_Destinatarios,
                    Asunto,
                    Cuerpo_Correo}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndEnviar_Correo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void Enviar_CorreoAsync(string Usuario, string Clave, string Correo_Remitente, string Correos_Destinatarios, string Asunto, string Cuerpo_Correo) {
        this.Enviar_CorreoAsync(Usuario, Clave, Correo_Remitente, Correos_Destinatarios, Asunto, Cuerpo_Correo, null);
    }
    
    /// <remarks/>
    public void Enviar_CorreoAsync(string Usuario, string Clave, string Correo_Remitente, string Correos_Destinatarios, string Asunto, string Cuerpo_Correo, object userState) {
        if ((this.Enviar_CorreoOperationCompleted == null)) {
            this.Enviar_CorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviar_CorreoOperationCompleted);
        }
        this.InvokeAsync("Enviar_Correo", new object[] {
                    Usuario,
                    Clave,
                    Correo_Remitente,
                    Correos_Destinatarios,
                    Asunto,
                    Cuerpo_Correo}, this.Enviar_CorreoOperationCompleted, userState);
    }
    
    private void OnEnviar_CorreoOperationCompleted(object arg) {
        if ((this.Enviar_CorreoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Enviar_CorreoCompleted(this, new Enviar_CorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/Listas_Internacionales", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode Listas_Internacionales(string Clave, string Nombre1, string Nombre2, string Apellido1, string Apellido2) {
        object[] results = this.Invoke("Listas_Internacionales", new object[] {
                    Clave,
                    Nombre1,
                    Nombre2,
                    Apellido1,
                    Apellido2});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginListas_Internacionales(string Clave, string Nombre1, string Nombre2, string Apellido1, string Apellido2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Listas_Internacionales", new object[] {
                    Clave,
                    Nombre1,
                    Nombre2,
                    Apellido1,
                    Apellido2}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndListas_Internacionales(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void Listas_InternacionalesAsync(string Clave, string Nombre1, string Nombre2, string Apellido1, string Apellido2) {
        this.Listas_InternacionalesAsync(Clave, Nombre1, Nombre2, Apellido1, Apellido2, null);
    }
    
    /// <remarks/>
    public void Listas_InternacionalesAsync(string Clave, string Nombre1, string Nombre2, string Apellido1, string Apellido2, object userState) {
        if ((this.Listas_InternacionalesOperationCompleted == null)) {
            this.Listas_InternacionalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListas_InternacionalesOperationCompleted);
        }
        this.InvokeAsync("Listas_Internacionales", new object[] {
                    Clave,
                    Nombre1,
                    Nombre2,
                    Apellido1,
                    Apellido2}, this.Listas_InternacionalesOperationCompleted, userState);
    }
    
    private void OnListas_InternacionalesOperationCompleted(object arg) {
        if ((this.Listas_InternacionalesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Listas_InternacionalesCompleted(this, new Listas_InternacionalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.equifax.cr/Estudio_360_Fisico", RequestNamespace="https://webservices.equifax.cr", ResponseNamespace="https://webservices.equifax.cr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode Estudio_360_Fisico(string referencia, string Cedula, string Usuario, string Clave, string Usuario_Datum) {
        object[] results = this.Invoke("Estudio_360_Fisico", new object[] {
                    referencia,
                    Cedula,
                    Usuario,
                    Clave,
                    Usuario_Datum});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEstudio_360_Fisico(string referencia, string Cedula, string Usuario, string Clave, string Usuario_Datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Estudio_360_Fisico", new object[] {
                    referencia,
                    Cedula,
                    Usuario,
                    Clave,
                    Usuario_Datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndEstudio_360_Fisico(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void Estudio_360_FisicoAsync(string referencia, string Cedula, string Usuario, string Clave, string Usuario_Datum) {
        this.Estudio_360_FisicoAsync(referencia, Cedula, Usuario, Clave, Usuario_Datum, null);
    }
    
    /// <remarks/>
    public void Estudio_360_FisicoAsync(string referencia, string Cedula, string Usuario, string Clave, string Usuario_Datum, object userState) {
        if ((this.Estudio_360_FisicoOperationCompleted == null)) {
            this.Estudio_360_FisicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstudio_360_FisicoOperationCompleted);
        }
        this.InvokeAsync("Estudio_360_Fisico", new object[] {
                    referencia,
                    Cedula,
                    Usuario,
                    Clave,
                    Usuario_Datum}, this.Estudio_360_FisicoOperationCompleted, userState);
    }
    
    private void OnEstudio_360_FisicoOperationCompleted(object arg) {
        if ((this.Estudio_360_FisicoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Estudio_360_FisicoCompleted(this, new Estudio_360_FisicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void estudio_personas_fisicasCompletedEventHandler(object sender, estudio_personas_fisicasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class estudio_personas_fisicasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal estudio_personas_fisicasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void obtener_datos_vehiculoCompletedEventHandler(object sender, obtener_datos_vehiculoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class obtener_datos_vehiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal obtener_datos_vehiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void categorias_informacionCompletedEventHandler(object sender, categorias_informacionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class categorias_informacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal categorias_informacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void estudio_personas_juridicasCompletedEventHandler(object sender, estudio_personas_juridicasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class estudio_personas_juridicasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal estudio_personas_juridicasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void categorias_informacion_juridicasCompletedEventHandler(object sender, categorias_informacion_juridicasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class categorias_informacion_juridicasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal categorias_informacion_juridicasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EFX_Validar_UsuarioCompletedEventHandler(object sender, EFX_Validar_UsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EFX_Validar_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EFX_Validar_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void Extranjeros_por_IdentificacionCompletedEventHandler(object sender, Extranjeros_por_IdentificacionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Extranjeros_por_IdentificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Extranjeros_por_IdentificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void Obtener_UsuarioWSCompletedEventHandler(object sender, Obtener_UsuarioWSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Obtener_UsuarioWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Obtener_UsuarioWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void Enviar_CorreoCompletedEventHandler(object sender, Enviar_CorreoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Enviar_CorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Enviar_CorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void Listas_InternacionalesCompletedEventHandler(object sender, Listas_InternacionalesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Listas_InternacionalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Listas_InternacionalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void Estudio_360_FisicoCompletedEventHandler(object sender, Estudio_360_FisicoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Estudio_360_FisicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Estudio_360_FisicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}
