//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace F2P.WAP.TU_Consulta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TU_ConsultaSoap", Namespace="http://tempuri.org/")]
    public partial class TU_Consulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ParametroBusquedaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidadorDeIdentidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReporteAproximacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReporteResultadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstadisticasUsoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TU_Consulta() {
            this.Url = global::F2P.WAP.Properties.Settings.Default.F2P_WAP_TU_Consulta_TU_Consulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ParametroBusquedaCompletedEventHandler ParametroBusquedaCompleted;
        
        /// <remarks/>
        public event ReporteCompletedEventHandler ReporteCompleted;
        
        /// <remarks/>
        public event ValidadorDeIdentidadCompletedEventHandler ValidadorDeIdentidadCompleted;
        
        /// <remarks/>
        public event ReporteAproximacionCompletedEventHandler ReporteAproximacionCompleted;
        
        /// <remarks/>
        public event ReporteResultadoCompletedEventHandler ReporteResultadoCompleted;
        
        /// <remarks/>
        public event EstadisticasUsoCompletedEventHandler EstadisticasUsoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParametroBusqueda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ParametroBusqueda(string xmlConsulta) {
            object[] results = this.Invoke("ParametroBusqueda", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ParametroBusquedaAsync(string xmlConsulta) {
            this.ParametroBusquedaAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void ParametroBusquedaAsync(string xmlConsulta, object userState) {
            if ((this.ParametroBusquedaOperationCompleted == null)) {
                this.ParametroBusquedaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametroBusquedaOperationCompleted);
            }
            this.InvokeAsync("ParametroBusqueda", new object[] {
                        xmlConsulta}, this.ParametroBusquedaOperationCompleted, userState);
        }
        
        private void OnParametroBusquedaOperationCompleted(object arg) {
            if ((this.ParametroBusquedaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametroBusquedaCompleted(this, new ParametroBusquedaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reporte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Reporte(string xmlConsulta) {
            object[] results = this.Invoke("Reporte", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReporteAsync(string xmlConsulta) {
            this.ReporteAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void ReporteAsync(string xmlConsulta, object userState) {
            if ((this.ReporteOperationCompleted == null)) {
                this.ReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReporteOperationCompleted);
            }
            this.InvokeAsync("Reporte", new object[] {
                        xmlConsulta}, this.ReporteOperationCompleted, userState);
        }
        
        private void OnReporteOperationCompleted(object arg) {
            if ((this.ReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReporteCompleted(this, new ReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidadorDeIdentidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidadorDeIdentidad(string xmlConsulta) {
            object[] results = this.Invoke("ValidadorDeIdentidad", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidadorDeIdentidadAsync(string xmlConsulta) {
            this.ValidadorDeIdentidadAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void ValidadorDeIdentidadAsync(string xmlConsulta, object userState) {
            if ((this.ValidadorDeIdentidadOperationCompleted == null)) {
                this.ValidadorDeIdentidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidadorDeIdentidadOperationCompleted);
            }
            this.InvokeAsync("ValidadorDeIdentidad", new object[] {
                        xmlConsulta}, this.ValidadorDeIdentidadOperationCompleted, userState);
        }
        
        private void OnValidadorDeIdentidadOperationCompleted(object arg) {
            if ((this.ValidadorDeIdentidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidadorDeIdentidadCompleted(this, new ValidadorDeIdentidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReporteAproximacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReporteAproximacion(string xmlConsulta) {
            object[] results = this.Invoke("ReporteAproximacion", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReporteAproximacionAsync(string xmlConsulta) {
            this.ReporteAproximacionAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void ReporteAproximacionAsync(string xmlConsulta, object userState) {
            if ((this.ReporteAproximacionOperationCompleted == null)) {
                this.ReporteAproximacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReporteAproximacionOperationCompleted);
            }
            this.InvokeAsync("ReporteAproximacion", new object[] {
                        xmlConsulta}, this.ReporteAproximacionOperationCompleted, userState);
        }
        
        private void OnReporteAproximacionOperationCompleted(object arg) {
            if ((this.ReporteAproximacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReporteAproximacionCompleted(this, new ReporteAproximacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReporteResultado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReporteResultado(string xmlConsulta) {
            object[] results = this.Invoke("ReporteResultado", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReporteResultadoAsync(string xmlConsulta) {
            this.ReporteResultadoAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void ReporteResultadoAsync(string xmlConsulta, object userState) {
            if ((this.ReporteResultadoOperationCompleted == null)) {
                this.ReporteResultadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReporteResultadoOperationCompleted);
            }
            this.InvokeAsync("ReporteResultado", new object[] {
                        xmlConsulta}, this.ReporteResultadoOperationCompleted, userState);
        }
        
        private void OnReporteResultadoOperationCompleted(object arg) {
            if ((this.ReporteResultadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReporteResultadoCompleted(this, new ReporteResultadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstadisticasUso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EstadisticasUso(string xmlConsulta) {
            object[] results = this.Invoke("EstadisticasUso", new object[] {
                        xmlConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EstadisticasUsoAsync(string xmlConsulta) {
            this.EstadisticasUsoAsync(xmlConsulta, null);
        }
        
        /// <remarks/>
        public void EstadisticasUsoAsync(string xmlConsulta, object userState) {
            if ((this.EstadisticasUsoOperationCompleted == null)) {
                this.EstadisticasUsoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstadisticasUsoOperationCompleted);
            }
            this.InvokeAsync("EstadisticasUso", new object[] {
                        xmlConsulta}, this.EstadisticasUsoOperationCompleted, userState);
        }
        
        private void OnEstadisticasUsoOperationCompleted(object arg) {
            if ((this.EstadisticasUsoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstadisticasUsoCompleted(this, new EstadisticasUsoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ParametroBusquedaCompletedEventHandler(object sender, ParametroBusquedaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametroBusquedaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametroBusquedaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ReporteCompletedEventHandler(object sender, ReporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ValidadorDeIdentidadCompletedEventHandler(object sender, ValidadorDeIdentidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidadorDeIdentidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidadorDeIdentidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ReporteAproximacionCompletedEventHandler(object sender, ReporteAproximacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReporteAproximacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReporteAproximacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ReporteResultadoCompletedEventHandler(object sender, ReporteResultadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReporteResultadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReporteResultadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EstadisticasUsoCompletedEventHandler(object sender, EstadisticasUsoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstadisticasUsoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstadisticasUsoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591